### ISSUE TITLE
Load plugins in cwd

### ISSUE THREAD

**Issue by egoist** [michael-ciniawsky/postcss-load-plugins#42]
When a CLI tool which uses this module is installed globally, it's supposed to find plugins in current working directory instead of the directory where the CLI is installed.

If I'm not mistaken, change `require(plugin)` to `requireCwd(plugin)` (https://github.com/sindresorhus/req-cwd) could solve this.

**Comment by michael-ciniawsky** [comment]
@egoist Please provide more info on this (setup), it's seems to work fine atm with e.g `postcss-cli`

**Comment by egoist** [comment]
I just tested it again, it does not work when you installed `postcss-cli` globally, [here](https://gist.github.com/egoist/45c5b32388f668b6b717ae55bc4b6368) is the exact steps to reproduce it.

**Comment by michael-ciniawsky** [comment]
Yep you're right 😛, hmm... we need to fix it somehow I  tae a 'deeper' look later today, any other options then `req-cwd` as alternatives (for consideration) ?

**Comment by egoist** [comment]
req-cwd is using [resolve-from](https://github.com/sindresorhus/resolve-from/blob/master/index.js), basically babel uses the same logic.

**Comment by egoist** [comment]
Or load plugins from [`path`](https://github.com/michael-ciniawsky/postcss-load-plugins/blob/master/index.js#L38) directory?

**Comment by michael-ciniawsky** [comment]
I will come to this soon I haven't forgotten 😛 yeah I that's what I intend to do but not 💯 if it works in all cases I need to test it with `gulp-postcss, postcss-loader, postcss-cli` for the first 2 maybe it stays as is and I add an additional `try/catch` to `resolve-from` before throwing an err :)

**Comment by thomheymann** [comment]
I think the correct behaviour here is to require dependencies relative to the config file (e.g. `.postcssrc` or `package.json` with postcss property) as it mirrors exactly what you would be getting when using a `postcss.config.js` file with `require` calls inlined. In most build tools that path is identical to `process.cwd()` so it's a good starting point to get a fix out. 

Babel uses the following function to get this behaviour and resolve modules relatively: https://github.com/babel/babel/blob/v6.26.0/packages/babel-core/src/helpers/resolve.js
(It's the exact same mechanism which that [req-cwd](https://github.com/sindresorhus/req-cwd) module uses)

I'm happy to send a PR for this. 

`postcss-load-options` package will also be affected I think. 

@egoist A temporary workaround is to use `postcss.config.js` file with `require` calls inlined instead of a JSON config. Not ideal obviously but in case it blocks you..

**Comment by thomheymann** [comment]
@michael-ciniawsky Any steer on this? Happy to sent a quick fix using `config.cwd` which I think is already passed through to both `postcss-load-plugins` and `postcss-load-options`. However, I think it's probably better to use `result.filepath` (path to loaded config) as a base to load dependencies from:
https://github.com/michael-ciniawsky/postcss-load-config/blob/003f65f46b89beef173b14fd79a7cef4600e9808/index.js#L53

To use it all three packages would need to be changed together though:
* postcss-load-config
* postcss-load-plugins
* postcss-load-options

Let me know your thoughts. Keen to get this fixed asap.

**Comment by sinisterstumble** [comment]
Done in #74 :100:

**Comment by michael-ciniawsky** [comment]
https://github.com/michael-ciniawsky/postcss-load-plugins/pull/74#issuecomment-404931669
